language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jitumani89docker/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jitumani89docker/docker-react npm run test